
package vue;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modele.DaoMembre;
import modele.Membre;
import modele.RegistreMembre;
import utilitaire.TableModelSpecial;

/**
 * @author Francisco Rojas
 */
public class GuiActualiser extends javax.swing.JFrame {
//attribute de la classe RegistreMembre
    private RegistreMembre membres = new RegistreMembre();
    /**
     * Creates new form GuiActualiser
     */
    public GuiActualiser() {
        try {
            initComponents();
            //Creer objDao
            DaoMembre objDAO = new DaoMembre();
            //Creer ResultSet rset
            ResultSet rset = objDAO.pListerTousMembres();
            //Prendre les enregistrements de la BD et creer un Registre de membres
            objDAO.resultSetToList(rset, membres);
            //appeler la méthode d'affichage dans le JTable
            dataBinding(membres.getListeMembres());
            //fermer la connexion
            objDAO.closeConnection();
        } catch (SQLException | IOException | ClassNotFoundException ex) {
            Logger.getLogger(GuiSupprimer.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtActualiser = new javax.swing.JTextField();
        btnActualiser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnFermer4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Choisissez le code du membre pour actuliser son statut:");

        btnActualiser.setText("Actualiser");
        btnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnFermer4.setText("Fermer");
        btnFermer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermer4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtActualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnActualiser)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(btnFermer4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtActualiser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualiser))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnFermer4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserActionPerformed
       try {
            //Creer objDAO
            DaoMembre objDAO = new DaoMembre();                        
            //Eliminer l'objet choisit par l'utilisateur
            objDAO.pActualiserStatus(txtActualiser.getText());
            //Creer un nouveau Registre pour actualiser l'affichage dans le JTable
            membres = new RegistreMembre();
            //afficher le tableau sans le membre eliminé 
            ResultSet rset = objDAO.pListerTousMembres();
            //Prendre les enregistrements de la BD et creer un Registre de membres
            objDAO.resultSetToList(rset, membres);            
           //appeler la méthode d'affichage dans le JTable
            dataBinding(membres.getListeMembres());
            objDAO.closeConnection();
            
        } catch (SQLException ex) {
            Logger.getLogger(GuiSupprimer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GuiSupprimer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GuiSupprimer.class.getName()).log(Level.SEVERE, null, ex);
        }  
        JOptionPane.showMessageDialog(null, "Membre actualisé avec succès!", "Message informatif", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnActualiserActionPerformed

    private void btnFermer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermer4ActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnFermer4ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton btnFermer4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtActualiser;
    // End of variables declaration//GEN-END:variables
//lier le JTable à la liste des membres pour l'affichage
    private void dataBinding(ArrayList<Membre> listeMembres){
        jTable1.removeAll();
        jTable1.setModel(new TableModelSpecial(listeMembres));
    }
}
