package vue;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modele.DaoMembre;
import modele.Membre;
import modele.RegistreMembre;
import utilitaire.TableModelSpecial;

/**
 * @author Francisco Rojas
 */
public class GuiConsulterStatus extends javax.swing.JFrame {
    //attribute de la classe RegistreMembre
    private RegistreMembre membres = new RegistreMembre();
    
    /**
     * Creates new form GuiConsulter
     */
    
    public GuiConsulterStatus() {
        try {
            initComponents();
            //Creer objDao
            DaoMembre objDAO = new DaoMembre();
            //Creer ResultSet rset
            ResultSet rset = objDAO.pListerTousMembres();
            //Prendre les enregistrements de la BD et creer un Registre de membres
            objDAO.resultSetToList(rset, membres);
            //appeler la méthode d'affichage dans le JTable
            dataBinding(membres.getListeMembres());
            //fermer la connexion
            objDAO.closeConnection();        
        } catch (SQLException | IOException | ClassNotFoundException ex) {
            Logger.getLogger(GuiConsulterStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        lblCritereConsultation = new javax.swing.JLabel();
        ComboBoxConsultation = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAfficher = new javax.swing.JButton();
        btnFermer1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCritereConsultation.setText("Choisissez un statut de consultation:");

        ComboBoxConsultation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "ARGENT", "REGULIER" }));
        ComboBoxConsultation.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAfficher.setText("Afficher");
        btnAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficherActionPerformed(evt);
            }
        });

        btnFermer1.setText("Fermer");
        btnFermer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermer1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblCritereConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(ComboBoxConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAfficher)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFermer1)
                .addGap(299, 299, 299))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCritereConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfficher))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnFermer1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficherActionPerformed
        try {
            DaoMembre objDAO = new DaoMembre();
            membres = new RegistreMembre();
            //Prendre l'option choisit par l'utilisateur dans le ComboBox
            String statut =(String) ComboBoxConsultation.getSelectedItem(); 
            //Envoyer la requête à la base de données pour obtenir les membres selon le statut
            ResultSet rset = objDAO.pListerCategorieMembres(statut);
            //Prendre les enregistrements (selon le statut) de la BD et creer un Registre de membres
            objDAO.resultSetToList(rset, membres);
            //appeler la méthode d'affichage dans le JTable
            dataBinding(membres.getListeMembres());
            
            //Affichage par console
            membres.afficherContenuRegistre();
            
            //fermer la connexion            
            objDAO.closeConnection();
            } catch (IOException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(GuiConsulterStatus.class.getName()).log(Level.SEVERE, null, ex);
            }         
           
    }//GEN-LAST:event_btnAfficherActionPerformed

    private void btnFermer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermer1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFermer1ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxConsultation;
    private javax.swing.JButton btnAfficher;
    private javax.swing.JButton btnFermer1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCritereConsultation;
    // End of variables declaration//GEN-END:variables

private void dataBinding (ArrayList <Membre> maListe){
    jTable1.removeAll();
    jTable1.setModel(new TableModelSpecial (maListe));
}

}
