
package vue;

import java.util.ArrayList;
import modele.Membre;
import modele.RegistreMembre;

/**
 * @author Francisco J. Rojas
 */
public class GuiPrincipal extends javax.swing.JFrame {
    //attribute de la classe RegistreMembre
    private RegistreMembre membres = new RegistreMembre();

    public GuiPrincipal() {     
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuInserer = new javax.swing.JMenu();
        MenuItemInsererMembres = new javax.swing.JMenuItem();
        MenuConsulter = new javax.swing.JMenu();
        MenuItemTous = new javax.swing.JMenuItem();
        MenuItemParStatut = new javax.swing.JMenuItem();
        MenuActualiser = new javax.swing.JMenu();
        MenuItemActualiserparCode = new javax.swing.JMenuItem();
        MenuSupprimer = new javax.swing.JMenu();
        MenuItemSupParCode = new javax.swing.JMenuItem();
        MenuQuitter = new javax.swing.JMenu();
        MenuItemQuitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionnaire Club Fleuristes");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconFleuriste.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        MenuInserer.setText("Inserer Membres");
        MenuInserer.setActionCommand("Inserer");
        MenuInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInsererActionPerformed(evt);
            }
        });

        MenuItemInsererMembres.setText("Inserer nouveau membre");
        MenuItemInsererMembres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemInsererMembresActionPerformed(evt);
            }
        });
        MenuInserer.add(MenuItemInsererMembres);

        jMenuBar1.add(MenuInserer);

        MenuConsulter.setText("Consulter");
        MenuConsulter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuConsulterActionPerformed(evt);
            }
        });

        MenuItemTous.setText("Tous les membres");
        MenuItemTous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemTousActionPerformed(evt);
            }
        });
        MenuConsulter.add(MenuItemTous);

        MenuItemParStatut.setText("Par statut");
        MenuItemParStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemParStatutActionPerformed(evt);
            }
        });
        MenuConsulter.add(MenuItemParStatut);

        jMenuBar1.add(MenuConsulter);

        MenuActualiser.setText("Actualiser");

        MenuItemActualiserparCode.setText("Par code");
        MenuItemActualiserparCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActualiserparCodeActionPerformed(evt);
            }
        });
        MenuActualiser.add(MenuItemActualiserparCode);

        jMenuBar1.add(MenuActualiser);

        MenuSupprimer.setText("Supprimer Membres");
        MenuSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSupprimerActionPerformed(evt);
            }
        });

        MenuItemSupParCode.setText("Par code");
        MenuItemSupParCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSupParCodeActionPerformed(evt);
            }
        });
        MenuSupprimer.add(MenuItemSupParCode);

        jMenuBar1.add(MenuSupprimer);

        MenuQuitter.setText("Quitter");
        MenuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuQuitterActionPerformed(evt);
            }
        });

        MenuItemQuitter.setText("Quitter l'application");
        MenuItemQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemQuitterActionPerformed(evt);
            }
        });
        MenuQuitter.add(MenuItemQuitter);

        jMenuBar1.add(MenuQuitter);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Element Inserer de la barre du menu principal
    private void MenuInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInsererActionPerformed
    
    }//GEN-LAST:event_MenuInsererActionPerformed
    //Element Consulter de la barre du menu principal
    private void MenuConsulterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuConsulterActionPerformed
        
    }//GEN-LAST:event_MenuConsulterActionPerformed
    //Element Supprimer de la barre du menu principal
    private void MenuSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSupprimerActionPerformed
        
    }//GEN-LAST:event_MenuSupprimerActionPerformed
   //Element Quitter de la barre du menu principal
    private void MenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuQuitterActionPerformed
        
    }//GEN-LAST:event_MenuQuitterActionPerformed
//option Inserer Membres dans le menu Inserer
    private void MenuItemInsererMembresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemInsererMembresActionPerformed
        GuiInserer objInserer = new GuiInserer();
        objInserer.setVisible(true);
    }//GEN-LAST:event_MenuItemInsererMembresActionPerformed
//option supprimer par code, dans le menu Supprimer
    private void MenuItemSupParCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSupParCodeActionPerformed
        GuiSupprimer objSupprimer = new GuiSupprimer(membres.getListeMembres());
        objSupprimer.setVisible(true);        
    }//GEN-LAST:event_MenuItemSupParCodeActionPerformed
//option du submenu de Consulter pour afficher tous les membres
    private void MenuItemTousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemTousActionPerformed
        GuiConsulterGeneral objConsulterG = new GuiConsulterGeneral(membres.getListeMembres());
        objConsulterG.setVisible(true);
    }//GEN-LAST:event_MenuItemTousActionPerformed
//option du submenu de Quitter pour sortir de l'application
    private void MenuItemQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuItemQuitterActionPerformed
//option du submenu de Consulter pour afficher des membres selon son statut
    private void MenuItemParStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemParStatutActionPerformed
       GuiConsulterStatus objConsulterS = new GuiConsulterStatus();
       objConsulterS.setVisible(true);
    }//GEN-LAST:event_MenuItemParStatutActionPerformed

    private void MenuItemActualiserparCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActualiserparCodeActionPerformed
        GuiActualiser objActualiser = new GuiActualiser();
        objActualiser.setVisible(true);
    }//GEN-LAST:event_MenuItemActualiserparCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuActualiser;
    private javax.swing.JMenu MenuConsulter;
    private javax.swing.JMenu MenuInserer;
    private javax.swing.JMenuItem MenuItemActualiserparCode;
    private javax.swing.JMenuItem MenuItemInsererMembres;
    private javax.swing.JMenuItem MenuItemParStatut;
    private javax.swing.JMenuItem MenuItemQuitter;
    private javax.swing.JMenuItem MenuItemSupParCode;
    private javax.swing.JMenuItem MenuItemTous;
    private javax.swing.JMenu MenuQuitter;
    private javax.swing.JMenu MenuSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
